language: objective-c
osx_image: xcode8.3
script:
  - xcodebuild build -project Demo-Objc/ScrollTab-Demo.xcodeproj -scheme ScrollTab-Demo -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' | xcpretty -s
